const express = require('express');
const multer = require('multer');
const cors = require('cors');
const fs = require('fs');
const path = require('path');
const fontkit = require('fontkit');
const sync = require('./scripts/sync-to-github');
require('dotenv').config();

const app = express();
const port = process.env.PORT || 3001;

// Configuração de diretórios (usando caminhos relativos à raiz do projeto)
const rootDir = path.join(__dirname, '..');
const cssDir = path.join(rootDir, 'CSS');
const fontesDir = path.join(rootDir, 'FONTES');
const uploadsDir = path.join(__dirname, 'uploads');
const fontsJsonPath = path.join(rootDir, 'fonts.json');

// Garantir que os diretórios existam
[cssDir, fontesDir, uploadsDir].forEach(dir => {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
});

app.use(cors());
app.use(express.json());

// Servir arquivos estáticos (CSS e fontes) para o frontend
app.use('/fonts-files', express.static(fontesDir));
app.use('/css-files', express.static(cssDir));
app.use('/FONTES', express.static(fontesDir));
app.use('/CSS', express.static(cssDir));

// Configuração do multer para upload de arquivos
const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, uploadsDir);
  },
  filename: (req, file, cb) => {
    cb(null, Date.now() + '-' + file.originalname);
  },
});

const upload = multer({ storage });

// Rota para listar fontes existentes
app.get('/api/fonts', (req, res) => {
  try {
    if (!fs.existsSync(fontsJsonPath)) {
      return res.json([]);
    }
    const data = JSON.parse(fs.readFileSync(fontsJsonPath, 'utf8'));
    // Garantir URLs completas para o frontend
    const fonts = data.map(f => ({
      ...f,
      cssUrl: `http://localhost:${port}/${f.cssUrl}`
    }));
    res.json(fonts);
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'Erro ao listar fontes.' });
  }
});

// Rota para upload de fontes
app.post('/api/upload', upload.array('fonts'), async (req, res) => {
  const { fontFamily: customDisplayName } = req.body;
  const files = req.files;

  if (!files || files.length === 0) {
    return res.status(400).json({ error: 'Nenhum arquivo enviado.' });
  }

  try {
    let detectedFamily = '';
    let cssContent = '/* Generated by BW8 Font System */\n';
    
    // Função auxiliar para detectar peso se o fontkit falhar ou para nomes específicos
    const getWeight = (name) => {
      const n = name.toLowerCase();
      if (n.includes('thin') || n.includes('hairline')) return 100;
      if (n.includes('extralight') || n.includes('ultralight')) return 200;
      if (n.includes('light')) return 300;
      if (n.includes('medium')) return 500;
      if (n.includes('semibold') || n.includes('demibold')) return 600;
      if (n.includes('bold')) return 700;
      if (n.includes('extrabold') || n.includes('ultrabold')) return 800;
      if (n.includes('black') || n.includes('heavy')) return 900;
      return 400; // regular
    };

    // Primeiro pass para detectar a família principal do primeiro arquivo válido
    for (const file of files) {
      try {
        const font = fontkit.openSync(file.path);
        detectedFamily = font.familyName;
        break;
      } catch (e) {}
    }

    const finalFamily = detectedFamily || customDisplayName || 'Unknown Font';
    const safeFolderName = finalFamily.toLowerCase().replace(/\s+/g, '-');
    const targetFontDir = path.join(fontesDir, safeFolderName);

    if (!fs.existsSync(targetFontDir)) {
      fs.mkdirSync(targetFontDir, { recursive: true });
    }

    for (const file of files) {
      const extension = path.extname(file.originalname).toLowerCase();
      const targetPath = path.join(targetFontDir, file.originalname);
      
      // Mover arquivo
      fs.renameSync(file.path, targetPath);
      
      let weight = 400;
      let style = file.originalname.toLowerCase().includes('italic') ? 'italic' : 'normal';

      try {
        const font = fontkit.openSync(targetPath);
        weight = font['OS/2'] ? font['OS/2'].usWeightClass : getWeight(file.originalname);
      } catch (err) {
        weight = getWeight(file.originalname);
      }

      const formatMap = {
        '.ttf': 'truetype',
        '.otf': 'opentype',
        '.woff': 'woff',
        '.woff2': 'woff2'
      };
      const format = formatMap[extension] || extension.replace('.', '');
      
      // Caminho relativo para o CSS
      const fontUrl = `../FONTES/${safeFolderName}/${file.originalname}`;
      
      cssContent += `
@font-face {
  font-family: '${finalFamily}';
  src: url('${fontUrl}') format('${format}');
  font-weight: ${weight};
  font-style: ${style};
  font-display: swap;
}
`;
    }

    const safeFileName = safeFolderName + '.css';
    fs.writeFileSync(path.join(cssDir, safeFileName), cssContent);

    // Atualizar registro JSON
    let fonts = [];
    if (fs.existsSync(fontsJsonPath)) {
      fonts = JSON.parse(fs.readFileSync(fontsJsonPath, 'utf8'));
    }

    const newFontEntry = {
      id: safeFolderName,
      displayName: customDisplayName || finalFamily,
      family: finalFamily,
      cssUrl: `css-files/${safeFileName}`
    };

    const index = fonts.findIndex(f => f.id === safeFolderName);
    if (index > -1) fonts[index] = newFontEntry;
    else fonts.push(newFontEntry);

    fs.writeFileSync(fontsJsonPath, JSON.stringify(fonts, null, 2));

    // Sincronizar com GitHub (em background)
    sync().catch(err => console.error('Erro na sincronização automática:', err));

    res.status(200).json({ 
      message: 'Fonte processada e registrada com sucesso!',
      font: newFontEntry
    });
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'Erro ao processar upload.' });
  }
});

// Iniciar o servidor
app.listen(port, () => {
  console.log(`Servidor rodando na porta ${port}`);
});
